---
language: python
services: docker

matrix:
  include:
    - os: linux
      dist: xenial

before_script:
  - cd ../
  - mv ansible-role-deploy-vmware-tools deploy-vmware-tools
  - cd deploy-vmware-tools

install:
  - pip install molecule docker

script:
  - molecule lint
